Traceback (most recent call last):
  File "/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/zposter38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import zfit
from zfit import z
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_2540/4054486904.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mimport[0m [0mtensorflow[0m [0;32mas[0m [0mtf[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mimport[0m [0mzfit[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;32mfrom[0m [0mzfit[0m [0;32mimport[0m [0mz[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/zfit/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     59[0m                        f" only with TF >= 2")
[1;32m     60[0m [0;34m[0m[0m
[0;32m---> 61[0;31m from . import (constraint, core, data, dimension, exception, func, loss,
[0m[1;32m     62[0m                minimize, param, pdf, sample, z)
[1;32m     63[0m [0;32mfrom[0m [0;34m.[0m[0mcore[0m[0;34m.[0m[0mdata[0m [0;32mimport[0m [0mData[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/zfit/constraint.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;32mimport[0m [0mtensorflow[0m [0;32mas[0m [0mtf[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[0;32m----> 5[0;31m [0;32mfrom[0m [0;34m.[0m[0mcore[0m[0;34m.[0m[0mconstraint[0m [0;32mimport[0m [0mGaussianConstraint[0m[0;34m,[0m [0mSimpleConstraint[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0;32mfrom[0m [0;34m.[0m[0mutil[0m [0;32mimport[0m [0mztyping[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/zfit/core/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m#  Copyright (c) 2021 zfit[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m from . import (basefunc, basemodel, baseobject, basepdf, data, integration,
[0m[1;32m      4[0m                interfaces, loss, operations, parameter, sample, space)

[0;32m/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/zfit/core/basefunc.py[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0;32mfrom[0m [0;34m.[0m[0;34m.[0m[0msettings[0m [0;32mimport[0m [0mztypes[0m[0;34m[0m[0;34m[0m[0m
[1;32m     17[0m [0;32mfrom[0m [0;34m.[0m[0;34m.[0m[0mutil[0m [0;32mimport[0m [0mztyping[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 18[0;31m [0;32mfrom[0m [0;34m.[0m[0mbasemodel[0m [0;32mimport[0m [0mBaseModel[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     19[0m [0;32mfrom[0m [0;34m.[0m[0minterfaces[0m [0;32mimport[0m [0mZfitFunc[0m[0;34m[0m[0;34m[0m[0m
[1;32m     20[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/zfit/core/basemodel.py[0m in [0;36m<module>[0;34m[0m
[1;32m     37[0m                               WorkInProgressError)
[1;32m     38[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mintegration[0m [0;32mas[0m [0mzintegrate[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 39[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0msample[0m [0;32mas[0m [0mzsample[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     40[0m [0;32mfrom[0m [0;34m.[0m[0mbaseobject[0m [0;32mimport[0m [0mBaseNumeric[0m[0;34m[0m[0;34m[0m[0m
[1;32m     41[0m [0;32mfrom[0m [0;34m.[0m[0mdata[0m [0;32mimport[0m [0mData[0m[0;34m,[0m [0mSampleData[0m[0;34m,[0m [0mSampler[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/zfit/core/sample.py[0m in [0;36m<module>[0;34m[0m
[1;32m     13[0m [0;32mfrom[0m [0;34m.[0m[0;34m.[0m[0mutil[0m[0;34m.[0m[0mcontainer[0m [0;32mimport[0m [0mconvert_to_container[0m[0;34m[0m[0;34m[0m[0m
[1;32m     14[0m [0;32mfrom[0m [0;34m.[0m[0;34m.[0m[0mutil[0m[0;34m.[0m[0mexception[0m [0;32mimport[0m [0mWorkInProgressError[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 15[0;31m [0;32mfrom[0m [0;34m.[0m[0mdata[0m [0;32mimport[0m [0mData[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     16[0m [0;32mfrom[0m [0;34m.[0m[0minterfaces[0m [0;32mimport[0m [0mZfitPDF[0m[0;34m,[0m [0mZfitSpace[0m[0;34m[0m[0;34m[0m[0m
[1;32m     17[0m [0;32mfrom[0m [0;34m.[0m[0mspace[0m [0;32mimport[0m [0mSpace[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/zfit/core/data.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;34m[0m[0m
[1;32m      7[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;32mimport[0m [0mtensorflow[0m [0;32mas[0m [0mtf[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0;32mimport[0m [0muproot[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/pandas/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     27[0m [0;34m[0m[0m
[1;32m     28[0m [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 29[0;31m     [0;32mfrom[0m [0mpandas[0m[0;34m.[0m[0m_libs[0m [0;32mimport[0m [0mhashtable[0m [0;32mas[0m [0m_hashtable[0m[0;34m,[0m [0mlib[0m [0;32mas[0m [0m_lib[0m[0;34m,[0m [0mtslib[0m [0;32mas[0m [0m_tslib[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     30[0m [0;32mexcept[0m [0mImportError[0m [0;32mas[0m [0me[0m[0;34m:[0m  [0;31m# pragma: no cover[0m[0;34m[0m[0;34m[0m[0m
[1;32m     31[0m     [0;31m# hack but overkill to use re[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/zposter38/lib/python3.8/site-packages/pandas/_libs/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m [0;34m[0m[0m
[1;32m     12[0m [0;34m[0m[0m
[0;32m---> 13[0;31m [0;32mfrom[0m [0mpandas[0m[0;34m.[0m[0m_libs[0m[0;34m.[0m[0minterval[0m [0;32mimport[0m [0mInterval[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m from pandas._libs.tslibs import (
[1;32m     15[0m     [0mNaT[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32mpandas/_libs/interval.pyx[0m in [0;36minit pandas._libs.interval[0;34m()[0m

[0;31mValueError[0m: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

